### ISSUE TITLE
Permission denied in role

### ISSUE THREAD

**Issue by Jonny007-MKD** [bodsch/ansible-glauth#8]
Hi bodsch,

when using your role I got several Permission denieds, so I had to add `become: true` at several places.
I'm installing it on a Debian system and not connecting as root.

I noticed you have several `become: false`; should `true` somehow be the default for the whole role?

**Comment by bodsch** [comment]
In which places exactly are you getting (which) errors?
The role has some tasks that definitely need root privileges, or just `become: true`.
I would like to improve and adapt my test cases here.

**Comment by Jonny007-MKD** [comment]
The error messages looked like this:

    TASK [bodsch.glauth : update package cache] **************************************************************************
    fatal: [server]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)"}
    
    TASK [bodsch.glauth : create glauth group] ***************************************************************************
    fatal: [server]: FAILED! => {"changed": false, "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "glauth"}
    
    TASK [bodsch.glauth : create plugins directory for installed version] ************************************************
    fatal: [server]: FAILED! => {"changed": false, "msg": "There was an issue creating /usr/local/bin/glauth/2.1.0/plugins as requested: [Errno 13] Permission denied: b'/usr/local/bin/glauth/2.1.0/plugins'", "path": "/usr/local/bin/glauth/2.1.0/plugins"}
    
    TASK [bodsch.glauth : create local facts] ****************************************************************************
    fatal: [server]: FAILED! => {"changed": false, "checksum": "7926ae6ec472dd1118fad8844fd10bbf74324709", "msg": "Destination /etc/ansible/facts.d not writable"}

I did not wait for every error, but added some `becomes` on spec.
This is the diff for tag 1.1.1:

    diff -r -U1 git/1.1.1/tasks/configure.yml ~/.ansible/roles/bodsch.glauth/tasks/configure.yml
    --- ./tasks/configure.yml	2023-01-16 21:12:13.082278989 +0100
    +++ ~/.ansible/roles/bodsch.glauth/tasks/configure.yml	2023-01-16 21:15:59.753599036 +0100
    @@ -3,2 +3,3 @@
     - name: create glauth configuration directory
    +  become: true
       ansible.builtin.file:
    @@ -11,2 +12,3 @@
     - name: create certificate directory
    +  become: true
       ansible.builtin.file:
    @@ -19,2 +21,3 @@
     - name: create glauth.conf
    +  become: true
       ansible.builtin.template:
    diff -r -U1 git/1.1.1/tasks/install/glauth.yml ~/.ansible/roles/bodsch.glauth/tasks/install/glauth.yml
    --- ./tasks/install/glauth.yml	2023-01-16 21:12:13.082278989 +0100
    +++ ~/.ansible/roles/bodsch.glauth/tasks/install/glauth.yml	2023-01-16 21:17:06.648236485 +0100
    @@ -8,2 +8,3 @@
         - name: propagate glauth binaries
    +      become: true
           ansible.builtin.copy:
    @@ -17,2 +18,3 @@
         - name: make files executable
    +      become: true
           ansible.builtin.file:
    @@ -24,2 +26,3 @@
     - name: create link to binary
    +  become: true
       ansible.builtin.file:
    diff -r -U1 git/1.1.1/tasks/install/main.yml ~/.ansible/roles/bodsch.glauth/tasks/install/main.yml
    --- ./tasks/install/main.yml	2023-01-16 21:12:13.082278989 +0100
    +++ ~/.ansible/roles/bodsch.glauth/tasks/install/main.yml	2023-01-16 21:17:49.276780402 +0100
    @@ -35,2 +35,3 @@
     - name: create glauth lib directory
    +  become: true
       ansible.builtin.file:
    @@ -52,2 +53,3 @@
     - name: create local facts
    +  become: true
       ansible.builtin.template:
    @@ -62,2 +64,3 @@
         - name: create systemd service unit
    +      become: true
           ansible.builtin.template:
    @@ -73,2 +76,3 @@
         - name: create glauth run configuration
    +      become: true
           ansible.builtin.template:
    @@ -89,2 +93,3 @@
         - name: create openrc service configuration
    +      become: true
           ansible.builtin.template:
    @@ -97,2 +102,3 @@
         - name: create openrc init configuration
    +      become: true
           ansible.builtin.template:
    @@ -104,3 +110,2 @@

    -
     ...
    diff -r -U1 git/1.1.1/tasks/install/plugins.yml ~/.ansible/roles/bodsch.glauth/tasks/install/plugins.yml
    --- ./tasks/install/plugins.yml	2023-01-16 21:12:13.082278989 +0100
    +++ ~/.ansible/roles/bodsch.glauth/tasks/install/plugins.yml	2023-01-16 21:18:01.323799762 +0100
    @@ -5,2 +5,3 @@
         - name: create plugins directory for installed version
    +      become: true
           ansible.builtin.file:
    @@ -13,2 +14,3 @@
         - name: copy plugins in place
    +      become: true
           ansible.builtin.copy:
    @@ -25,2 +27,3 @@
     - name: create link to plugins
    +  become: true
       ansible.builtin.file:
    diff -r -U1 git/1.1.1/tasks/prepare.yml ~/.ansible/roles/bodsch.glauth/tasks/prepare.yml
    --- ./tasks/prepare.yml	2023-01-16 21:13:32.532863071 +0100
    +++ ~/.ansible/roles/bodsch.glauth/tasks/prepare.yml	2023-01-16 21:16:45.113972274 +0100
    @@ -23,2 +23,3 @@
     - name: update package cache
    +  become: true
       ansible.builtin.package:
    @@ -27,2 +28,3 @@
     - name: install dependency
    +  become: true
       ansible.builtin.package:
    @@ -115,2 +117,3 @@
         - name: create glauth group
    +      become: true
           ansible.builtin.group:
    @@ -121,2 +124,3 @@
         - name: create glauth user
    +      become: true
           ansible.builtin.user:
    @@ -139,2 +143,3 @@
     - name: create install directory
    +  become: true
       ansible.builtin.file:
    @@ -147,2 +152,3 @@
     - name: create ansible facts directory
    +  become: true
       ansible.builtin.file:

**Comment by bodsch** [comment]
I have added the `become: true` extension in https://github.com/bodsch/ansible-glauth/commit/17349ce9530d570346fd751c2af9dffcfa2074b8.
Once the workflows are green, I will release a new version.

**Comment by bodsch** [comment]
closed with release [1.2.0](https://github.com/bodsch/ansible-glauth/releases/tag/1.2.0)
