### ISSUE TITLE
glauth_frontends is unused

### ISSUE THREAD

**Issue by Jonny007-MKD** [bodsch/ansible-glauth#9]
I found an inconsistency between the documentation in README.md and the template definitions for glauth.conf:

The templates contain references to `glauth_config.ldap` and `.ldaps`, whereas the docs mention `glauth_frontends` with some rather weird nested parameters. `glauth_frontend` isn't used anywhere, though.

https://github.com/bodsch/ansible-glauth/blob/14b5e4d36c90934285e4dd42dc61b8b361e190dc/vars/main.yml#L91-L99

https://github.com/bodsch/ansible-glauth/blob/9f58ee87244720a160fd646fa1deedbdf418ae6a/templates/glauth/glauth.d/ldap.j2#L2-L8

I could write a PR to fix it, but I don't know your intention: Did you want to move the stuff from `glauth_config` to `glauth_frontends` or should `glauth_frontends` be removed?

**Comment by bodsch** [comment]
Thanks for your advice.
`glauth_frontends` should be removed, it has no relation to glauth.

**Comment by bodsch** [comment]
The variable was removed in https://github.com/bodsch/ansible-glauth/commit/17349ce9530d570346fd751c2af9dffcfa2074b8
